# Generated by Django 2.2.16 on 2020-11-10 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bossoidc2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='keycloak',
            table='bossoidc_keycloak',
        ),
    ]
